name: Bug report 🐛
description: Create a bug report.
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/straetus/api/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current behavior 😯
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior 🤔
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Steps to reproduce 🕹
      description: |
        Provide steps (preferable with links) on how to reproduce this bug.

        Issues that we can't reproduce will be closed.
      value: |
        Steps:

        1.
        2.
        3.
        4.
  - type: textarea
    attributes:
      label: Context 🔦
      description: What are you trying to accomplish? How has this issue affected you? Providing context helps us come up with a solution that is more useful in the real world.
